version: '3'

services:
  exercise-toes-dynamodb:
    container_name: exercise_toes_dynamodb
    image: amazon/dynamodb-local
    ports:
      - "8005:8005"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

  exercise-toes-web:
    restart: always
    build: .
    depends_on:
      - exercise-toes-dynamodb
    container_name: exercise_toes_web
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
    working_dir: /app
    environment:
      - PYTHONPATH=/var/runtime:/app
    expose:
      - "5005"
    command: bash -c "source /root/.bashrc && invoke start"
    ports:
      - "5005:5005"
    links:
      - exercise-toes-dynamodb:exercise-toes-dynamodb

volumes:
    dynamodata: {}
